#!/usr/bin/env python3

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import os

def plot_speedup_analysis():
    """
    Plot speedup analysis results from CSV files generated by speedup test scripts
    """

    # Check for results file (try different names)
    possible_files = [
        'results/speedup_results.csv',
        'results/speedup_results_quick.csv'
    ]

    results_file = None
    for file in possible_files:
        if os.path.exists(file):
            results_file = file
            break

    if results_file is None:
        print("Error: No speedup results file found!")
        print("Looked for:")
        for file in possible_files:
            print(f"  - {file}")
        print("Please run one of the speedup test scripts first:")
        print("  - ./speedup_test_timeout.sh")
        print("  - ./speedup_test_quick.sh")
        return

    print(f"Using results file: {results_file}")

    # Read the CSV data
    try:
        data = pd.read_csv(results_file)
        print(f"Loaded data for {len(data)} thread configurations")
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return

    # Clean the data - remove failed/timeout entries
    clean_data = data[
        (data['actual_speedup'] != 'failed') &
        (data['actual_speedup'] != 'timeout') &
        (data['actual_speedup'] != 'invalid') &
        (data['actual_speedup'] != 'build_failed') &
        (data['actual_speedup'] != 'parse_failed') &
        (data['actual_speedup'] != 'no_output') &
        (data['actual_speedup'] != 'no_data') &
        (data['actual_speedup'] != 'calc_failed') &
        (data['actual_speedup'] != 'no_baseline')
    ].copy()

    if len(clean_data) == 0:
        print("No valid data found in results file!")
        print("All tests may have failed. Check the output files in results/ directory.")
        return

    # Convert to numeric
    try:
        clean_data['actual_speedup'] = pd.to_numeric(clean_data['actual_speedup'])
        clean_data['theoretical_speedup'] = pd.to_numeric(clean_data['theoretical_speedup'])
        clean_data['efficiency'] = pd.to_numeric(clean_data['efficiency'])
        clean_data['total_time'] = pd.to_numeric(clean_data['total_time'])
        clean_data['dot_time'] = pd.to_numeric(clean_data['dot_time'])
    except Exception as e:
        print(f"Error converting data to numeric: {e}")
        return

    print(f"Plotting data for {len(clean_data)} successful configurations")

    # Create the plots
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle('MNIST Neural Network Speedup Analysis (M4 MacBook)', fontsize=16)

    threads = clean_data['threads']

    # Plot 1: Speedup Comparison
    ax1.plot(threads, clean_data['theoretical_speedup'], 'b-o', label='Theoretical (Amdahl)', linewidth=2, markersize=6)
    ax1.plot(threads, clean_data['actual_speedup'], 'r-s', label='Actual Measured', linewidth=2, markersize=6)
    ax1.plot(threads, threads, 'g--', label='Ideal Linear', alpha=0.7, linewidth=1)
    ax1.set_xlabel('Number of Threads')
    ax1.set_ylabel('Speedup')
    ax1.set_title('Theoretical vs Actual Speedup')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim(1, max(threads))

    max_speedup = max(max(clean_data['actual_speedup']), max(clean_data['theoretical_speedup']))
    ax1.set_ylim(0.8, max(max_speedup, max(threads)) * 1.1)

    # Plot 2: Parallel Efficiency
    efficiency_percent = clean_data['efficiency'] * 100
    ax2.plot(threads, efficiency_percent, 'purple', marker='o', linewidth=2, markersize=6)
    ax2.axhline(y=100, color='g', linestyle='--', alpha=0.7, label='Perfect Efficiency')
    ax2.axhline(y=80, color='orange', linestyle=':', alpha=0.7, label='80% Threshold')
    ax2.set_xlabel('Number of Threads')
    ax2.set_ylabel('Efficiency (%)')
    ax2.set_title('Parallel Efficiency')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    ax2.set_xlim(1, max(threads))
    ax2.set_ylim(0, 110)

    # Plot 3: Execution Time Breakdown
    width = 0.8
    ax3.bar(threads, clean_data['total_time'], width, alpha=0.7, label='Total Time', color='lightblue')
    ax3.bar(threads, clean_data['dot_time'], width, alpha=0.8, label='Dot() Time', color='darkblue')
    ax3.set_xlabel('Number of Threads')
    ax3.set_ylabel('Time (seconds)')
    ax3.set_title('Execution Time Breakdown')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # Plot 4: Speedup vs Efficiency Scatter
    sc = ax4.scatter(clean_data['actual_speedup'], efficiency_percent,
                     c=threads, cmap='viridis', s=100, alpha=0.7)
    ax4.set_xlabel('Actual Speedup')
    ax4.set_ylabel('Efficiency (%)')
    ax4.set_title('Speedup vs Efficiency (colored by thread count)')
    ax4.grid(True, alpha=0.3)
    cbar = plt.colorbar(sc, ax=ax4)
    cbar.set_label('Thread Count')

    plt.tight_layout()

    # Save the plot
    plt.savefig('results/speedup_analysis.png', dpi=300, bbox_inches='tight')
    plt.savefig('results/speedup_analysis.pdf', bbox_inches='tight')
    print("\nPlots saved as:")
    print("- results/speedup_analysis.png")
    print("- results/speedup_analysis.pdf")

    # Show the plot
    plt.show()

    # Print summary statistics
    print("\n=== SPEEDUP ANALYSIS SUMMARY ===")
    max_speedup_val = clean_data['actual_speedup'].max()
    max_speedup_threads = clean_data.loc[clean_data['actual_speedup'].idxmax(), 'threads']
    max_theoretical = clean_data['theoretical_speedup'].max()
    max_efficiency = clean_data['efficiency'].max()
    max_eff_threads = clean_data.loc[clean_data['efficiency'].idxmax(), 'threads']

    print(f"Maximum actual speedup: {max_speedup_val:.2f}x at {max_speedup_threads} threads")
    print(f"Maximum theoretical speedup: {max_theoretical:.2f}x")
    print(f"Best efficiency: {(max_efficiency * 100):.1f}% at {max_eff_threads} threads")

    # Find optimal thread count (best efficiency > 80% or highest speedup)
    high_eff = clean_data[clean_data['efficiency'] >= 0.8]
    if len(high_eff) > 0:
        optimal_threads = high_eff.loc[high_eff['actual_speedup'].idxmax(), 'threads']
        optimal_speedup = high_eff.loc[high_eff['actual_speedup'].idxmax(), 'actual_speedup']
        optimal_efficiency = high_eff.loc[high_eff['actual_speedup'].idxmax(), 'efficiency'] * 100
        print(f"Recommended optimal: {optimal_threads} threads (speedup: {optimal_speedup:.2f}x, efficiency: {optimal_efficiency:.1f}%)")
    else:
        print(f"Best performance: {max_speedup_threads} threads (speedup: {max_speedup_val:.2f}x, efficiency: {(clean_data.loc[clean_data['actual_speedup'].idxmax(), 'efficiency'] * 100):.1f}%)")

    avg_percentage = clean_data['percentage'].mean()
    print(f"\nData shows parallel portion: {avg_percentage:.1f}% of total execution time")
    print(f"M4 chip utilization: {(max_speedup_val / 4 * 100):.1f}% of theoretical 4-core potential")

    # Show Amdahl's law validation
    print(f"\n=== AMDAHL'S LAW VALIDATION ===")
    f = avg_percentage / 100.0
    theoretical_4_core = 1 / ((1 - f) + f / 4)
    actual_4_core = clean_data[clean_data['threads'] == 4]['actual_speedup'].iloc[0] if len(clean_data[clean_data['threads'] == 4]) > 0 else "N/A"

    print(f"Parallel fraction (f): {f:.3f}")
    print(f"Theoretical 4-core speedup: {theoretical_4_core:.2f}x")
    if actual_4_core != "N/A":
        print(f"Actual 4-core speedup: {actual_4_core:.2f}x")
        print(f"Efficiency vs theory: {(actual_4_core / theoretical_4_core * 100):.1f}%")

if __name__ == "__main__":
    plot_speedup_analysis()